### ISSUE TITLE
Convenient way to add a new timezone

### ISSUE THREAD

**Issue by dossjb** [kerberos-io/web#1]
In the United States there are no choices for timezones.  It would be nice to be able to be able to add new time zones without going to the source code.  I did add a time zone that would have been in my area to the "timezone.xml" file but I never noticed the correct time and date showing for the images.

**Comment by cedricve** [comment]
Hey dossjb,

Thank you for your report, indeed the timeszones for US are missing; we will add them. Please notice that the settings page is only for the machinery. This means that the timezone you select there will be used for the machinery only (the time condition). However to change the timezone of the webapplication, you will need to edit the app.php configuration file: https://kerberosio.zendesk.com/hc/en-us/articles/203301462-How-to-change-timezone-of-the-web-interface.

We will look into this, if we can reuse the timezone from the settings page also for the webapplication. However we will loose some flexibility, if we do so. But I think it's logical that the webinterface always has the same timezone as the machinery. But for portabality reasons, e.g. if you would setup the webinterface on a dedicated server, you don't want to have the settings enabled.

Regards
Cédric

**Comment by cedricve** [comment]
We've integrated the use of the timezone both for the machinery and web interface. We also added more timezones. This will be included in the next release 1.0.2.
