### ISSUE TITLE
Configuration reverted at a previous time

### ISSUE THREAD

**Issue by cpetra** [kerberos-io/web#100]
Sometimes when enabling/disabling the interface the configuration is reverted at a previous one. I am using google chrome as browser. For example, if I have selected 1280x720 IP Camera at a previous moment in time and then used a different camera configuration (680x385), which works correctly from that moment onwards, when using the enable/disable button in the web page the camera is again set up at 1280x720. (Seems to be the same for other configuration parameters).

Best Regards,
Constantin

**Comment by cedricve** [comment]
@cpetra can you send us more information about your system/installation? Which OS and system (microcontroller / docker / server).

**Comment by cpetra** [comment]
Hi Cedric,

I have an Orange Pi Zero running armbian:
Linux orangepizero 3.4.113-sun8i #18 SMP PREEMPT Thu Jun 15 02:16:06 CEST 2017 armv7l armv7l armv7l GNU/Linux

The web is cloned from git, while machinery I don't remember exactly but I think it was also cloned from git and built locally (had a hard time matching versions).

I don'k know how much it matters - the system is in a remote location, running through an openvpn connection using an Internet stick, and the connection is quite slow (100KBps).

Best Regards,
Constantin

**Comment by kocis73** [comment]
Same as me.
isn't it like https://github.com/kerberos-io/web/issues/111 ?

**Comment by cedricve** [comment]
@cpetra @kocis73 indeed same issue let's continue on #111.

**Comment by cedricve** [comment]
@cpetra installing the machinery should be ok again for armbian using version 2.5.0.
https://github.com/kerberos-io/machinery/issues/134
