### ISSUE TITLE
Stream can be accessed without authentication

### ISSUE THREAD

**Issue by shivpatel** [kerberos-io/web#102]
Using the latest Dockerized version.

In Google Chrome I am able to view the live camera stream via (/stream) without logging in via the homepage. Looks like this route is not protected by authentication?

**Comment by cedricve** [comment]
by default it's not protected, however you should enable it by using the settings page.

**Comment by shivpatel** [comment]
Ah a separate HTTP Basic Auth is available under Advanced Settings -> Stream -> Down Arrow.

Doesn't seem like the best authentication/security implementation but it'll do for now. I'll try to put in a PR if I find a way to protect the stream route using the existing login.

**Comment by cedricve** [comment]
Thanks would be a great PR, let me know if I can help @shivpatel
