### ISSUE TITLE
Autoremove old images/video within Docker Containers?

### ISSUE THREAD

**Issue by clessley** [kerberos-io/web#104]
#58 related, also [Generic ](https://doc.kerberos.io/2.0/installation/Generic#auto-removal) documentation.

I do not see the autoremoval.sh script within the Docker container file structure indicated with the two references above. Should I just create the script in the /home location within the Docker container using Docker bash?

Theoretical setup:
Headless Ubuntu Server 500 GB running Docker + Portainer.
Container 1 (web): 25 GB with autoremoval.sh would use 90% of container = 22.5GB of container.
Container 2 (web): 25 GB with autoremoval.sh would use 50% of container = 12.5GB of container.
And so on.
Total use of Swarm = ~ 50 GB for web/images/video (sans machinery containers).

**Comment by cedricve** [comment]
hey @clessley, there is a autoremoval function running on booting the machinery containers:
 https://github.com/kerberos-io/machinery/blob/master/docker/run.sh.

**Comment by clessley** [comment]
Thanks, I see it. Perfect.
