### ISSUE TITLE
Config Error on Login

### ISSUE THREAD

**Issue by squiggie** [kerberos-io/web#110]
Brand new install of docker images from latest. 

I installed kerberos/web:latest & kerberos/machinery:latest.

Machinery is exposing ports on the bridge of 80 and 8889. 

After figuring out I needed to change the default.conf file of nginx from
`proxy_pass http://machinery:8889;`
to
`proxy_pass http://172.17.0.3:8889;`
I'm finally able to connect to the web and nginx stays running.

Now I'm getting an error on the web.
> Oops, something went wrong 
One or more config files are missing in /etc/opt/kerberosio/config. 
Please check if the .xml files are available.

Where do I find the xml files?

**Comment by cedricve** [comment]
hey @squiggie, thanks for reporting let me check.

**Where do I find the xml files?**

They should exist in **/etc/opt/kerberosio/config**

**Comment by squiggie** [comment]
@cedricve that directory is empty within the docker web image.

**Comment by cedricve** [comment]
hey @squiggie, sorry for the late response. After reviewing it looks like you didn't use docker-compose? You'll need to do this as we shared resources between containers (e.g. the config directory). That might also caused your first issue; ip address.

https://doc.kerberos.io/2.0/installation/Docker
