### ISSUE TITLE
Implement docker image for ARMv6 and ARMv7

### ISSUE THREAD

**Issue by cedricve** [kerberos-io/web#120]
Started working on a Docker ARMv6 compatible image (RPi1 and RPi Zero - W), but getting errors when executing

    composer install

The Dockerfile can be found here, any help is welcome https://github.com/kerberos-io/web/blob/develop/docker/Dockerfile-arm

This issue is linked to https://github.com/kerberos-io/docker/issues/3

**Comment by ChieftainY2k** [comment]
Hi Cédric, what kind of errors do you get ?

**Comment by cedricve** [comment]
hey @ChieftainY2k, actually this is already resolved. We now support armv8 and armv7

https://hub.docker.com/r/kerberos/kerberos/tags/
