### ISSUE TITLE
Configuration not saved

### ISSUE THREAD

**Issue by marcel31415** [kerberos-io/web#124]
Any changes to the configuration by web-interface are not saved.
I have had the problem before and reflashed the card. After that i was able to make changes which were saved.
With updating to 2.7.0 I encoutered the same problem: Any changes are not saved.
Changing anything by SSH/Terminal works as it should. Files are writable.

**Comment by cedricve** [comment]
Can you try with a blank installation, from 2.6.1 and upgrade it again to 2.7.0. Just to be sure you're not using an old image (which might be the case).

**Comment by marcel31415** [comment]
That is exactly what i did.

**Comment by cedricve** [comment]
hmm that's not good.. i'll try it myself. keep you posted.

**Comment by cedricve** [comment]
just tried it myself and it looks like it is working now. however I confirm the issue was there in a previous installation. can you retry your process and confirm my statement @marcel31415 ? Any way thank you very much for your time.

**Comment by marcel31415** [comment]
Can i trace/debug  the save process?

**Comment by marcel31415** [comment]
Will get back to you.

No, thanks to you!!

**Comment by marcel31415** [comment]
Fresh Installation of 2.7 works and saves changes.
I will now flash 2.6.1 and update it to 2.7.0

**Comment by marcel31415** [comment]
I reflashed the card with 2.7.0 yesterday.
But the problem reoccurs!
Encore the machinery stops working from time to time. I will change the RaspberryPi to exclude the possibility that the Pi is the Problem.
So: No changes are saved and the machinery stops working. 

Can i provide any information / data that might help you? 
[kerberosio-configuration.zip](https://github.com/kerberos-io/web/files/2064795/kerberosio-configuration.zip)

**Comment by cedricve** [comment]
Hey thanks, well it's hard to simulate if you do not give detailed steps. I've been testing it for a couple of times but didn't noticed any weird.. 

⁣Sent from BlueMail ​

**Comment by cedricve** [comment]
can we have have a teamviewer session right now?

**Comment by marcel31415** [comment]
of course, how can i send you the id and pw?

**Comment by cedricve** [comment]
send it to cedric@verstraeten.io

**Comment by marcel31415** [comment]
Problem solved:
If you place a file which dos not belong to the "real" configuration at _/data/machinery/config/_, any changes will not be saved! 

I have just tested it (together with cedricve) and as soon as the foreign object (my script file) is removed, everything works as it should!

Thanks @ cedricve for his help, time, and patience!
