### ISSUE TITLE
Explain cron task

### ISSUE THREAD

**Issue by nicolas-f** [kerberos-io/web#13]
Hi,

I would like to know why Kerberos is requesting the web page http://hades.kerberos.io each 3 minutes ?

```sh
#############################################
# Execute HTTP request to hades
##
sleep $[$RANDOM%170] && /bin/phantomjs /home/bash/hades.js
```

**Comment by cedricve** [comment]
Hello Nicolas

This is used to keep the WIFI connection alive, as some users reported that the WIFI dongle timed out after some minutes (even if the timeout function was disabled). You can replace this with every HTTP request you like.

Regards
