### ISSUE TITLE
After install Login screen not shown 

### ISSUE THREAD

**Issue by alasso** [kerberos-io/web#130]
**Describe the bug**
Hi, I just burned an kerberos.io image an run it. I can access trough safari browser but there is no login window, just a blank (with no menu nor input boxes)

**To Reproduce**
1. Go to http://192.168.1.132
2. Blank screen (red, but without any component inside)

**Expected behavior**
Login screen

**Screenshots**
![2018-07-13 10 26 10](https://user-images.githubusercontent.com/415620/42693988-3d8a5a54-8687-11e8-8fc4-bc2f01b4ba75.png)

**Desktop (please complete the following information):**
 - kerberos.io image burned with etcher.io
 - Browser: safari on macos
 - Version: 11.1.2

**Comment by cedricve** [comment]
hey can you check the console and verify it also the case in chrome?

**Comment by alasso** [comment]
Thanks!

It seams that there is a problem with the path to javascript components.
I don't know where to touch to resolve it

<img width="1232" alt="2018-07-14 12 49 00" src="https://user-images.githubusercontent.com/415620/42726048-64fdace8-8764-11e8-9884-95a900a1d0e0.png">

**Comment by cedricve** [comment]
Correct, something went wrong while building the new release and we didn't get notified. Solved the issue and uploading a new image. Keep you posted.

**Comment by alasso** [comment]
Ok! Thanks a lot for your help.

**Comment by cedricve** [comment]
should be fixed, can you please test?

**Comment by alasso** [comment]
Thnks!
As I can't log in, I am unable to upgrade from web. Is there any way to do it via ssh? Should I burn again an image?

**Comment by cedricve** [comment]
Yes unfortunately you'll need to reflash

**Comment by alasso** [comment]
I tested and it is working fine.

Thanks a lot!
