### ISSUE TITLE
Slider won't come up

### ISSUE THREAD

**Issue by stephanealpha** [kerberos-io/web#15]
After installing as stated in the doc (with some minor changes due to use of Raspbian instead of Arch), everything works fine except the upper slider on the image visualization page.

Safari debugger says:
TypeError: $('#timer-slider').slider is not a function. (In '$('#timer-slider').slider', '$('#timer-slider').slider' is undefined) images.js:77

Any idea ?

**Comment by stephanealpha** [comment]
Problem solved by copying manually the file bootstrap-slider.js in js directory.

I may need to learn more about nom and bower.

**Comment by cedricve** [comment]
Hello Stephanealpha

Indeed there was a problem at our side, it looks like a dependency have been changed.
We've update the version number.

https://github.com/kerberos-io/web/commit/c8822c3c5ac3e3d6382d734ee71caab96c8b21e3

Thanks for the notice!
Cédric
