### ISSUE TITLE
Https proxy not working

### ISSUE THREAD

**Issue by cwjackso** [kerberos-io/web#158]
When using docker and a https proxy such as traefik the laravel framework outputs all usages of 

`{URL:to("\")`

With the wrong scheme - this used to work on old version by adding the env variable 

`KERBEROSIO_SECURE_SSL=true`

This no longer is the case.

**Comment by cedricve** [comment]
We made some changes to the docker file, will have a look @cwjackso

**Comment by cwjackso** [comment]
Switched to the `:amd-64` tag in docker and that works ok. Uses a different base image and is about 3x the size though! @cedricve

**Comment by cedricve** [comment]
We fixed it last night can you give a try?

Kind regards,
Verstraeten Cédric

**Comment by cwjackso** [comment]
Yep - that seems to be working now Thank you. What is the difference between the 2 images by the way, is smaller one more efficient now?

**Comment by cedricve** [comment]
yes, you can check the github repo to see what is happening in the dockerfile. We are using a multi stage dockerfile, so we only include the dependencies needed to tun kerberos open source.

Kind regards,
Verstraeten Cédric
