### ISSUE TITLE
Translate full interface for pt-br support

### ISSUE THREAD

**Issue by mikaelhadler** [kerberos-io/web#28]
Hello,
I wonder if there is the possibility of translating the entire interface of the 'app/views', prontifico me translate all fields to en, but I want to know, I modify the static files or can develop a module for further translation in other countries?

**Comment by cedricve** [comment]
Hello mikael, 

Yes, please check  your zendesk ticket. To update the language for all the views you need to translate the language files. For portugese you will find them at app/lang/pt.

Please update it at the develop branch.

**Comment by cedricve** [comment]
still open.. @mikaelhadler

**Comment by mikaelhadler** [comment]
Okay, sorry for the delay.
