### ISSUE TITLE
Improve behaviour when /capture is empty

### ISSUE THREAD

**Issue by Orabig** [kerberos-io/web#29]
For now, the dashboard looks as if nothing is working when /capture is empty.
I thing a more explicit message would be a good idea to help new-comers to understand that the configuration is ok, even without any image (or just tell "the .../capture folder is empty or not found")

**Comment by cedricve** [comment]
Yes, that's correct. The loading should stop.

**Comment by cedricve** [comment]
![screen shot 2016-05-11 at 14 28 19](https://cloud.githubusercontent.com/assets/1546779/15181017/28d1ecee-1785-11e6-9627-6b60ac0efa31.png)
