### ISSUE TITLE
no feedback when the live view is not working

### ISSUE THREAD

**Issue by Orabig** [kerberos-io/web#31]
If the live view is not working for some reason (incorrect configuration, 8888 port not opened...), the progress is never ending, so the user is not sure if the network is just slow, and is given no clue about what is not working.
I would suggest a placeholder saying "HOST:8888 is unreachable" which : 
1- Informs the user that something is not working
2- Informs the user that he should make sure that the port 8888 is opened (which is obvious for 80, but not for 8888, as I didn't see it in the docs for instance. I'm not the only one obviously : #25 )

**Comment by cedricve** [comment]
Good point, as we're working with canvas on the dashboard, we can draw it directly.

**Comment by cedricve** [comment]
Fixed in 56a687d596acdc507e02512ff389542b2a412518

![screen shot 2016-05-11 at 12 32 36](https://cloud.githubusercontent.com/assets/1546779/15178841/6d1b3188-1778-11e6-8db9-091d9b2d6b5f.png)
