### ISSUE TITLE
no feedback when the machinery is not running

### ISSUE THREAD

**Issue by Orabig** [kerberos-io/web#32]
Whenever the machinery (kerberosio process) is down, the 'system' page in the web says it's running, which could be misleading.

The 'system' page should give correct informations about the process (if it's running).

**Comment by cedricve** [comment]
What do you mean with process is running, currently there is only the mention about the version. Maybe we'll need to add an extra section with running services (ps -aux or htop).

For the system page we use [the Linfo library](https://github.com/jrgp/linfo), when running on Linux we can use the `getProcessStats` or `getServices`. You can find a [complete list of methods here](https://gist.github.com/woganmay/815e9f74d134b7327b0d).

**Comment by Orabig** [comment]
Yes, adding some `ps -aux | greo kerberosio | grep -v kerberosio` would be the solution, I think.

>  currently there is only the mention about the version available on the system
Untrue : The `System` page is telling : 

```
Kerberos.io has two services running: the web and the machinery
```

**Comment by cedricve** [comment]
Hmm that's a good one, didn't expect that someone would interpret it like that; but yes I confirm your reasoning. My purpose with this message was that I only wanted to note that Kerberos.io comes with two services.

I confirm that it's confusing and that we should fix this.

**Comment by cedricve** [comment]
![screen shot 2016-05-12 at 09 51 12](https://cloud.githubusercontent.com/assets/1546779/15207566/5af7e5dc-1827-11e6-9059-1612b208d51a.png)
![screen shot 2016-05-12 at 09 51 30](https://cloud.githubusercontent.com/assets/1546779/15207567/5b141892-1827-11e6-94bb-424268b604a6.png)
