### ISSUE TITLE
The logs are not visible thru the web interface

### ISSUE THREAD

**Issue by Orabig** [kerberos-io/web#33]
It would be great to have access to the machinery logs, as a checkbox 'logging' is shown in 'configuration' part, but the user can't see the effects, except with a ssh connection to the raspberry.

**Comment by cedricve** [comment]
To view the logs from the system page, a user can use the button **Download system files**. What you propose is to make an inline display, just like Travis-CI does?

![logtravis](https://cloud.githubusercontent.com/assets/1546779/14852431/83e7fb32-0c86-11e6-9900-89cfd552288b.PNG)

**Comment by Orabig** [comment]
Yes, it would be awsome for debbuging :)

**Comment by cedricve** [comment]
I'll take this one on me if you're ok with that?

**Comment by Orabig** [comment]
sure

**Comment by cedricve** [comment]
![screen shot 2016-05-11 at 19 57 22](https://cloud.githubusercontent.com/assets/1546779/15190982/ded7f52e-17b2-11e6-967a-0e1089089436.png)
![screen shot 2016-05-11 at 19 57 28](https://cloud.githubusercontent.com/assets/1546779/15190985/e01c3968-17b2-11e6-9e9f-3815b2fdd078.png)
