### ISSUE TITLE
no feedback when the configuration can't be changed

### ISSUE THREAD

**Issue by Orabig** [kerberos-io/web#34]
If the machinery config folder is read-only, then the 'update' on configuration page silently fails.
A message should warn the user that something is wrong.

**Comment by cedricve** [comment]
Ok for me, good point!

**Comment by cedricve** [comment]
![screen shot 2016-05-12 at 10 29 05](https://cloud.githubusercontent.com/assets/1546779/15208553/8b57597e-182c-11e6-87be-1fbda7d9fd93.png)
