### ISSUE TITLE
Settings and System are not available is case of config problem

### ISSUE THREAD

**Issue by Orabig** [kerberos-io/web#35]
In several case, the web dashboard can be avaiable, while clicking on 'settings' or 'system' has no effect at all.

The cases when this is happening should be enumerated, but I've noticed that it seems to happen :
 - when the config folder defined in `app.php` is missing or incorrect
 - when the capture folder is empty (to be confirmed)

**Comment by cedricve** [comment]
Error views are created, application is interupted if some ocnfiguration is missing.

![screen shot 2016-05-11 at 15 24 25](https://cloud.githubusercontent.com/assets/1546779/15183472/767ca900-1791-11e6-9177-5d13506aad27.png)
![screen shot 2016-05-11 at 15 25 15](https://cloud.githubusercontent.com/assets/1546779/15183474/7a21289c-1791-11e6-9773-75cbfff5142a.png)
![screen shot 2016-05-11 at 15 54 58](https://cloud.githubusercontent.com/assets/1546779/15183480/7f12dd1e-1791-11e6-92b3-ac3ac3a77713.png)

**Comment by Orabig** [comment]
Totally cool. This is perfect :)
