### ISSUE TITLE
parameter config in app.php can't be changed at all

### ISSUE THREAD

**Issue by Orabig** [kerberos-io/web#38]
config = /etc/opt/kerberosio/config by default

It's pointless to change this parameter, as there is no way AFAIK to change this path in the machinery.
Am I wrong ?

**Comment by cedricve** [comment]
When doing `make install` it will move the configuration files to that directory on the filesystem. However it can be possible that a user doesn't want to install the project so only `make` the project.
My conclusion: It wouldn't be a good idea to hardcode this..

What do you think?

**Comment by Orabig** [comment]
Good point. I close this one.
(In fact, the title was not well chosen. My main point here was that I wondered how to change the machinery config path)
