### ISSUE TITLE
Dashboard javascript error in Firefox

### ISSUE THREAD

**Issue by marcusklaas** [kerberos-io/web#42]
`Error: Script error for "heatmap", needed by: app/controllers/dashboard_heatmap
http://requirejs.org/docs/errors.html#scripterror`

Doesn't seem to happen in Chrome..

**Comment by cedricve** [comment]
Thanks for reporting @marcusklaas I'll check this

**Comment by cedricve** [comment]
@marcusklaas  do you have an adblocker installed?

**Comment by marcusklaas** [comment]
Yes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Van: Cédric VerstraetenVerzonden: woensdag 11 mei 2016 2:48 PMAan: kerberos-io/webBeantwoorden: kerberos-io/webCc: Marcus Klaas de Vries; MentionOnderwerp: Re: [kerberos-io/web] Dashboard javascript error in Firefox (#42)@marcusklaas  do you have an adblocker installed?

—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by cedricve** [comment]
please remove heatmap.js from the adblocker, we wil have this fixed in next release.

56a687d596acdc507e02512ff389542b2a412518
