### ISSUE TITLE
Move the graphs of the dashboard to a "statistics" panel

### ISSUE THREAD

**Issue by Orabig** [kerberos-io/web#43]
Those graphs could be replaced by the latest "events" detected

**Comment by cedricve** [comment]
Any ideas what should come in place? We still have the live stream, heatmap and latest sequence.

**Comment by muten84** [comment]
I think that could be useful to split last events,live stream and heatmap sections  in separate widgets and enable users to store each widget position on the dashboard (left up corner, right up, etc)

Another way could be to leave the same widget behavior and to enable users to set a default widget view (live stream or last sequence or heatmap) in conjunction with multiple instance of same widget.

The result in any case is that each user can dynamically set what he prefers.

**Comment by cedricve** [comment]
Hmm good point, we should think about how and where to store that information. Knowing that the webinterface only depends on the xml config files and the capture directory.

**Comment by muten84** [comment]
A Json file?

**Comment by cedricve** [comment]
good idea, that will work. We can store it in the public folder and make it read-write.

**Comment by cedricve** [comment]
Will be transferred to our cloud application, where it will make more sense..
