### ISSUE TITLE
Too many url redirects error on logon without internet connection

### ISSUE THREAD

**Issue by martinl** [kerberos-io/web#49]
steps to reproduce:
- connect rpi to wifi router without internet connection (tested with both wired and wifi)
- boot kerberos.io
- try to login to webinterface with root/root

result: browser reports too many url redirects error and fails to logon

I can ssh to rpi and motion detection works / images are saved - only web interface is affected

If I connect rpi / kerberos to wifi network with internet connection and boot, logon to webinterface works without problems

**Comment by cedricve** [comment]
Thanks for the report @martinl I'll check it out..

**Comment by cedricve** [comment]
982aaa7e3779cff29f1e5c79673b6d0f2a06a5e1
