### ISSUE TITLE
Live view only works in Chrome.

### ISSUE THREAD

**Issue by cedricve** [kerberos-io/web#56]
In Internet Explorer and Firefox (and maybe other browsers), the live view doesn't work properly. This needs to be investigated.

**Comment by jpbell** [comment]
I just wanted to say it seems to work for me on Firefox (49.02), and Chrome, however it does not work on Edge, not sure about IE.

**Comment by cedricve** [comment]
Thanks for the update @jpbell, I'll check what goes wrong.

**Comment by Tviljan** [comment]
Why is this closed? Live view does not work on MS Edge

**Comment by cedricve** [comment]
Having other priorities for now, we will not fix this as probably future MS browsers will start supporting it.
Use Chrome or Firefox instead.
