### ISSUE TITLE
Settings page redirects to dashboard

### ISSUE THREAD

**Issue by cedricve** [kerberos-io/web#57]
This is an issue which was resolved some months ago; adding spaces breaks the system. We've just found out that when entering a / in the instance name we have the same behaviour.

**Comment by Baby38** [comment]
Just installed Kerberos io and all is fine except that Bug : Settings page redirects to dashboard ! Interested in how solve that issue ? Thx

**Comment by cedricve** [comment]
Can you send me your /var/www/web/storage/logs/laravel.log file?

**Comment by Baby38** [comment]
Hello

 

Here is the laravel.log file

 

Thx a lot to help me

 

 



Jean Gaillat

0683023050

 <http://jeangaillat.wordpress.com/> Voir mon Blog ICI

 

 

 

De : Cédric Verstraeten [mailto:notifications@github.com] 
Envoyé : mercredi 21 juin 2017 10:59
À : kerberos-io/web
Cc : Baby38; Comment
Objet : Re: [kerberos-io/web] Settings page redirects to dashboard (#57)

 

Can you send me your /var/www/web/storage/logs/laravel.log file?
