### ISSUE TITLE
Set a limit in GUI on the number of stored images

### ISSUE THREAD

**Issue by TopperHarry** [kerberos-io/web#58]
such that the SD card on i.e. Raspberry pi does not get full.

**Comment by cedricve** [comment]
@TopperHarry I think you're using Raspbian? On KiOS we have a script running that starts removing old images, when disk is getting full. You can find it over here.

https://github.com/kerberos-io/kios/blob/master/board/common/overlay/etc/init.d/S85machinery#L29-L33
