### ISSUE TITLE
change base url

### ISSUE THREAD

**Issue by ytzelf** [kerberos-io/web#59]
Hello,

What would be the process to change the base url to /kerberos.

I'm having difficulties to deploy kerberos-io behind a nginx reverse proxy ie
https://xxxxx.yyyyy.zz/kerberos/ redirects to http://localhost:545/kerberos

Thanks!

**Comment by cedricve** [comment]
I would suppose that you just put it under a directory called /kerberos and point the root of your domain to a directory lower.

**Comment by ytzelf** [comment]
that would work assuming that the web interface doesnt use anything above public/ and that there s no absolute path in the files.

Will try and report back

**Comment by ytzelf** [comment]
OK I got it working on the local machine i can reach the login page.
Had to change the includes in index.php
require __DIR__.'/../kerberos_src/web/bootstrap/autoload.php';
$app = require_once __DIR__.'/../kerberos_src/web/bootstrap/start.php';

As well as the capture folder in app.php
However I can't seem to redirect with nginx; here's the relevant configuration
        ```
location ^~ /kerberos/ {
                access_log              /var/log/nginx/kerberos_access_redirect.log;
                error_log               /var/log/nginx/kerberos_error_redirect.log debug;
                proxy_pass              http://127.0.0.1:545;
        }
```

As well as the kerberos server configuration
```
server {
        listen                          127.0.0.1:545;
        root                            /var/www/;
        index                           index.php index.html index.htm;
        access_log                      /var/log/nginx/access_kerberos.log;
        error_log                       /var/log/nginx/error_kerberos.log debug;

        location /kerberos {
                autoindex on;
                try_files $uri $uri/ /kerberos/index.php?$query_string;
        }

        location ~ \.php$ {
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_param SCRIPT_FILENAME $request_filename;
                include fastcgi_params;
        }
}

```

**Comment by cedricve** [comment]
Hmm that's true, never tried it before tbh. Looks like you're on the right way. I'll take a look when I'm home. Let me know if you found the issue.

**Comment by ytzelf** [comment]
I understand it's not the priority as kerberos is meant to run stand alone but I already have a server and would like to run multiple instance of kerberos on it.
I'm guessing the url in app.php has sth to do with this as well. Will keep a close eye on this thread as this is pretty much required for my use case.

I'll keep trying when I get home I can't do more than text based browsing now...

Thanks a lot for your assistance

**Comment by cedricve** [comment]
Hey @ytzelf  do you have any update on this ticket?

**Comment by GrossoMoreira** [comment]
I was able to set up an apache proxy to run kerberos-io on a docker container and access it through https.
Apparently the URLs in kerberos-io's HTML are absolute and explicit HTTP, so I had to configure apache to preserve the host name and to replace all occurrences of http with https.

For anyone interested, here's my virtual host config:

`<IfDefine SSL>`
`<IfDefine !NOSSL>`
`<VirtualHost MY_DOMAIN:443>`
`        ServerName MY_DOMAIN`
`        ErrorLog /var/log/apache2/error_log`
`        TransferLog /var/log/apache2/access_log`

`        SSLEngine on`

`        SSLCertificateFile /etc/apache2/ssl.crt/MY_CERT.crt`
`        SSLCertificateKeyFile /etc/apache2/ssl.key/MY_CERT.key`

`        CustomLog /var/log/apache2/ssl_request_log   ssl_combined`

`        <Location />`
`                ProxyPreserveHost On`
`                UseCanonicalName Off`

`                ProxyPass http://DOCKER_CONTAINER_IP:80/`
`                ProxyPassReverse http://DOCKER_CONTAINER_IP:80/`
`                #SetOutputFilter  proxy-html    `
`                ProxyHTMLEnable On`
`                RequestHeader unset Accept-Encoding`

`                AddOutputFilterByType SUBSTITUTE text/html`
`                Substitute s|http://|https://|ni`
`        </Location>`

`</VirtualHost>`
`</IfDefine>`
`</IfDefine>`
