### ISSUE TITLE
Convert to AngularJS 2 and Laravel 5.3 REST API 

### ISSUE THREAD

**Issue by cedricve** [kerberos-io/web#70]
Currently the web repository is written in Laravel 4.2 and BackboneJS. For performance reason we will move a lot more functionality to client side.

**Comment by samvloeberghs** [comment]
@cedricve #itsJustAngular

**Comment by cedricve** [comment]
I need a coding wizard like your for this issue ;)

**Comment by mikaelhadler** [comment]
@cedricve You need to Angular JS 2, why not Angular 1.x ? 👍

**Comment by cedricve** [comment]
@muten84 yeah that would be great! We're also considering to create it with React and React Native. But obviously it's just a perference, Angular2 would be great a choice as well.  Key concern is that it should be lightweight, no-database approach (rely completely on the filesystem and file), and have a simple and highly flexible API (Laravel is the definetely the way to go). From my opinion we should only rewrite the Front-End, and upgrade the Backend-end (Laravel) to latest version.

**Comment by muten84** [comment]
@cedricve   Ok for Laravel, by the way GWT is not a substitute for Lavarel it's just a Java2JS compiler with JRE emulation API. Angular is lightweight framework and is intended to simplify the development of components and modules in more structured way, altough it's not targeted to enterprise applcation models. You can think about kerberos-web with major complexity and with more scalability needs in terms of frontend modules.

However if the number of kerberos-web modules and components will not grows Angular should be the right choice.

As i can see from the Angular roadmap this month should be released Angular 4.x .... there is a nice blog post explaining why they jump from 2.x to 4.x. What i mean is that maybe it's convenient to wait for this release before start writing code and deal with just announced breaking changes. As i can read they advance to new Typescript version and changed some core API. What do you think?

**Comment by SoullessWaffle** [comment]
FWIW, Laravel [has selected](https://twitter.com/laracasts/status/758396261225623552) [Vue.js](https://vuejs.org/v2/guide/) as its front-end framework of choice.
You can find detailed comparisons with Angular 1.x, 2.x and React [here](https://vuejs.org/v2/guide/comparison.html).

**Comment by cedricve** [comment]
Thanks for sharing @SoullessWaffle we'll take a look!

**Comment by samvloeberghs** [comment]
@SoullessWaffle Laravel has NO direct link with vue.js architecture wise. Hence, I don't see how any frontend framework can be associated as a framework of choice for any other backend framework. Laravel providing a out of the box solution for vue does not mean you should use vue!
