### ISSUE TITLE
Blank welcome page when upgrading from 2.1.0

### ISSUE THREAD

**Issue by HanYangZhao** [kerberos-io/web#79]
I upgrade the web interface by deleting everything under /var/www/ and then download the new version and extract the tar file. Not sure what's going on. Machinery upgrade seems to work
![web](https://cloud.githubusercontent.com/assets/4143538/23200087/6704d89e-f8a0-11e6-907b-cb52e8755817.jpg)

**Comment by cedricve** [comment]
hey @HanYangZhao please clear your cache, this is describe in the **upgrade procedure**.
https://doc.kerberos.io/2.0/installation/upgrade
