### ISSUE TITLE
Sort order in the day view

### ISSUE THREAD

**Issue by kr15h** [kerberos-io/web#8]
It would be great if it would be possible to order the list of captured frames in descending order as, as far as I can imagine, the latest activations are the ones people might be looking for first (also me). The time slider on the top is great, but whenever one selects time, it would be great to browse the images from the selected time towards past.

**Comment by cedricve** [comment]
New option to sort ascending or descending

**Comment by cedricve** [comment]
I'll add this in next release.

**Comment by cedricve** [comment]
Will not be implemented
