### ISSUE TITLE
100% cpu usage an never ending webpage load

### ISSUE THREAD

**Issue by bbbenji** [kerberos-io/web#82]
This happens on a freshly made SD card using late KIOS. I have reflash several times and different SD cards. Rebooting temporarily fixed it and leaves the web page accessible. Soon after issues occur.

PHP error log:

`2017/04/17 18:10:43 [error] 881#0: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/web/app/repositories/imagehandler/ImageFileSystemHandler.php on line 97" while reading response header from upstream, client: 192.168.1.199, server: kerberos.rpi, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "192.168.1.174", referrer: "http://192.168.1.174/settings"`

Upping the max execution time to 300 did not work, it wouldn't be a solution anyway.

**Comment by cedricve** [comment]
Behaviour is random, we've figured out over teamviewer. Problem resolved itself after x seconds, might be related to a networking issue.
