### ISSUE TITLE
No data available everywhere.

### ISSUE THREAD

**Issue by bottiger** [kerberos-io/web#83]
I have installed kerberos-io and it's working great. However, I do have some issues with the web part.

Whats working:

- The web interface works and i can click around.
- I can watch the live stream
- I can read and write settings to the kerberos-io config files.
- I can read the state of various system  parameters in the system page.

What is not working

- All the graphs in the dashboard say "no data available"
- The "web" image in the configuration page is missing
- The image in the "hull" editor is missing.

It feels like that some sort of persistence/caching folder have the wrong permissions.

I do get a warning which says "Hey, your disk is almost full. Please remove some images.." but since my capture folder is on a mounted 4 TB network drive there are at least a few hundred GB og free space.

I running everything on raspian OS.

**Comment by cedricve** [comment]
@bottiger sorry for the late response, well it looks like you didn't changed the symbol link of the web interface. By default the web interface will look for images/videos in `/etc/opt/kerberosio/capture`. Next to updating the configuration files of the machinery, you'll also need to update the filesystem path or symbol link to point to your external drive.
