### ISSUE TITLE
[Bug] heatmap radius

### ISSUE THREAD

**Issue by znorris** [kerberos-io/web#84]
This is a minor bug.

Steps to reproduce:
1. Move the heatmap radius slider to a new position.
2. Click Update
3. See that the slider has returned to the position it was at previous to our action in step 1.
4. See that  the heatmap as changed back to its original radius.
5. Refresh the page.
6. See that the radius slider and the heatmap are using the radius that was set by our actions in step 1.

Numbers 3 and 4 are unexpected and appear to be a bug.

**Comment by cedricve** [comment]
Will be fixed in next release, issue is due to caching.

**Comment by cedricve** [comment]
fixed in version 2.3.0, KiOS 2.4.0
