### ISSUE TITLE
Adding expandable clusters of captured frames in the day view

### ISSUE THREAD

**Issue by kr15h** [kerberos-io/web#9]
It is not so easy to get a string internet connection where I am and for the day view I'd prefer to load a thumbnail of an activity that could be expanded and only then all the frames of the activity would be loaded. That would save a lot of traffic and also make the UI a lot more responsive.

**Comment by kr15h** [comment]
I'm thinking of the cloud interface here too. + I will look into it and propose a solution.

**Comment by cedricve** [comment]
That sounds interesting, if you could add a solution for the web, I can also port it to the cloud application. Currently there is a javascript class that uses html 5 canvas, to draw the images. This needs to be replaced with a server side generated thumbnail. Probably you will need to expand the ImageController and use the PHP gd class.

**Comment by cedricve** [comment]
I've been thinking about this: it will indeed be more user-friendly to only get a single thumbnail (e.g. a frame in the middle of the detection), and after clicking on the thumbnail the full sequence is shown.

Great idea!

**Comment by Orabig** [comment]
+1 for me about the last comment
This would be much more user frienly (and will use much less bandwidth)

**Comment by cedricve** [comment]
I'll work on this one.

**Comment by cedricve** [comment]
Followup #45
