### ISSUE TITLE
Unable to get latest sequence with basic auth.

### ISSUE THREAD

**Issue by Stubbs** [kerberos-io/web#99]
I'd like to be able to display the latest sequence inside my home automation control panel, I've already got the live stream, but I'd like to be able to see the last event too.

I can't use basic auth headers when making an API call, I just get the login page.

**Comment by cedricve** [comment]
Correct, we'll adjust this REST endpoint so that it can be retrieved by using Basic Auth. Keep you posted @Stubbs.
